### ISSUE TITLE
地図のラベルクリック時に祭り詳細画面を表示する

### ISSUE THREAD

**Issue by ymits** [codeforchiba/feschibal#14]
現在は地図のマーカークリック時にのみ祭り詳細画面を表示させているが、ラベルクリック時にも祭り詳細画面を表示させる

**Comment by HiroAsa** [comment]
ラベルが以外とでかいので検索リストに番号付けてその番号だけ表示でも良いのでは。。。

**Comment by ymits** [comment]
#17 にて地図に表示されている祭りデータを拡大域によってまとめる機能を追加してみます。

祭りデータがすっきり表示されていればラベルも邪魔ではなくなるかもしれないですね。
