### ISSUE TITLE
詳細画面のアイコンに「神輿」を追加したい

### ISSUE THREAD

**Issue by misopeso** [codeforchiba/feschibal#151]
祭りを見に行くときの判断基準としてあってもいいかな、と。

**Comment by YasushiTakemoto** [comment]
![2016-07-02 18 05 48](https://cloud.githubusercontent.com/assets/5886469/16539487/b0b0b06e-407f-11e6-932e-e2ffdacf4d5f.png)
作りました！

**Comment by misopeso** [comment]
@YasushiTakemoto PNG でしかダウンロードできないのですが、SVG でもらえますか？

**Comment by misopeso** [comment]
@YasushiTakemoto Slack で見つけたので OK ですー！
