### ISSUE TITLE
MA11 受賞コンテンツを作成する

### ISSUE THREAD

**Issue by misopeso** [codeforchiba/feschibal#163]
MA11 シビックテック部門賞 & MA11 CIVICTECH for Citizen賞の受賞報告コンテンツをトップページかどこかにのせたいです。

**Comment by YasushiTakemoto** [comment]
こちらにメインイメージのデータ入っていますのでよろしくお願いします。
https://www.dropbox.com/sh/n5km090lsczvmwy/AACUEJ9vRvW-x_2nS4V5utWja?dl=0

![160611_01](https://cloud.githubusercontent.com/assets/5886469/15983132/ae3c495e-2fd8-11e6-8e2a-2d3ce80c7ecc.jpg)
