### ISSUE TITLE
メディア掲載情報コンテンツを作成する

### ISSUE THREAD

**Issue by misopeso** [codeforchiba/feschibal#182]
月刊事業構想にのったので、トップページ辺りに表示したいです。

**Comment by YasushiTakemoto** [comment]
こちらにメインイメージのデータ入っていますのでよろしくお願いします。
https://www.dropbox.com/sh/n5km090lsczvmwy/AACUEJ9vRvW-x_2nS4V5utWja?dl=0

![160611_02](https://cloud.githubusercontent.com/assets/5886469/15983159/4e414e18-2fd9-11e6-9a03-c0789a2cbf3b.jpg)
