### ISSUE TITLE
Nexus 5 でカルーセルが期待通りに動作しない

### ISSUE THREAD

**Issue by misopeso** [codeforchiba/feschibal#236]
Nexus 5 で、カルーセルが一度矢印かポッチを触ってやらないと、うまくscrollしていないようです。

**Comment by snakamu** [comment]
調査途中経過(7/12)

ブラウザでも確認していると、
ブラウザ種類とriot.jsのreadyイベントにより、
正常、誤動作が分かれてしまう。

１、
 this.on('update', function() {
　 〜
 }
chrome 誤動作
safari 正常
firefox 正常

２、
this.on(‘mount’, function() {
　 ～
 }
chrome 正常
safari 誤動作
firefox 誤動作

✳︎IEは後ほど。

**Comment by misopeso** [comment]
ブラウザにより、拾うイベントが違うってことなんですかね。
だから jQuery を使っていたのかな。。。

**Comment by misopeso** [comment]
riot.js のバグかもしれないので、バージョンアップを検討してもいいかもしれません。

**Comment by snakamu** [comment]
jQueryのReadyに戻し、再度複数ブラウザ確認しましたが、
chrome 正常,safari 誤動作,firefox 誤動作であったため、
swiperの方の問題のようです。

riot.jsも最新にしてみましたが、改善しませんでした。

**Comment by snakamu** [comment]
IEでも確認したのですが、top画像が崩れております。
カルーセル対応前の状態に戻しても、同様のため、元々の問題でしょうか。

![ie](https://cloud.githubusercontent.com/assets/11253385/16770146/881e8450-4886-11e6-872b-248639249147.png)

**Comment by misopeso** [comment]
ごちゃごちゃしてきたので、整理しましょう。

事象: カルーセルのオートスクロールが動作しない。ただし、左右のボタン、及びナビゲーションのぽっちを押すと動作開始する。

経過: Swiper の初期化タイミングにより、動作が異なる。

余談: IE だとそもそも表示がおかしい。

ちなみに、表示のおかしい IE のバージョンは幾つですか？

**Comment by snakamu** [comment]
整理頂いた通りです。Swiper周りで引き続き調査続けます。
IEのバージョンは11で確認しました。
宜しくお願い致します。

**Comment by misopeso** [comment]
IE の件は、別 Issue にしましょう。 #243 を作ったので、こちらに画像を添付しておいてもらえますか？

**Comment by snakamu** [comment]
swiperのautoscrollですが、jQueryでいうところの
ready(DOMツリーの構築後)でなく、load(画像,コンテンツの読み込み完了後)ですと、
ブラウザに関係なく正しく動作します。

riot.js公式サイトのライフサイクルイベントは全て試しましたが、
$(window).load()(window.onload)と同じ動きをするものはありませんでした。

**Comment by misopeso** [comment]
これ、試しました？

http://riotjs.com/forum/#!/using:event-when-image-finished-l

画像毎にイベント管理するしかできないとなると面倒ではありますね。。。

**Comment by misopeso** [comment]
これ、普通に window.onload でやるってことなのかも。それなら、できそうですか？

**Comment by snakamu** [comment]
window.onload(jQueryの$(window).load())ですと、
ブラウザに関係なく、auto pagenationうまく始動します。
ただ、ポッチが最後にいきなり表示されるのが少々気になります。

**Comment by misopeso** [comment]
> ただ、ポッチが最後にいきなり表示されるのが少々気になります。

このタイムラグが結構大きいのでしょうか？ 動かないよりまし、なレベルなら、一旦この対応しちゃいましょう。

**Comment by snakamu** [comment]
タイミング的には、Map読み込み直後という感じで個人的にはそこまで気にならないのですが、
Safariだけ左からポッチが飛んできたような動きをします。

一度pushしますので、ご確認頂いてよろしいでしょうか。

**Comment by misopeso** [comment]
確かに Safari は、そんな動きしますね。なんか、斬新！w

ロード直後にすぐ使うような UI でもないので、このまま行きましょうか。
