### ISSUE TITLE
README.mdにDockerの情報を載せたい

### ISSUE THREAD

**Issue by seitaro1227** [codeforchiba/feschibal#290]
1. slack#infra
   
   ```
   docker build -t festival-server-dev:v1 -f Dockerfile.dev .
   docker run -d -p 9000:9000 -v $(pwd)/app:/var/www/feschibal/app festival-server-dev:v1
   ```
2. https://hub.docker.com/r/codeforchiba/feschibal/
   
   などから情報をまとめてます。
- メモ
  
  ```
  git clone https://github.com/codeforchiba/feschibal.git
  docker build -t festival-server-dev:v1 -f Dockerfile.dev .
  # OR docker pull codeforchiba/festival-server-dev
  # ↑ (TODO: docker pushしたら)
  docker run -d -p 9000:9000 -v $(pwd)/app:/var/www/feschibal/app festival-server-dev:v1
  ```
  
  で動くかもしれないので、検証して追記します。

**Comment by seitaro1227** [comment]
#299 がDockerHubに適応された為以下のコマンドで開発環境を立ち上げられるようになりました。

```
git clone https://github.com/codeforchiba/feschibal.git
cd feschibal
docker run -d -p 9000:9000 -p 35729:35729 -v $(pwd)/app:/var/www/feschibal/app codeforchiba/feschibal
```

@misopeso 
ちなみに
リリースモジュールの生成
は
お祭りデータをコンバートする

```
docker run --rm -v $(pwd)/data:/var/www/feschibal/data -t festival-server-dev grunt build-data
```

で代用可能でしょうか？

リリースモジュールでの動作確認
はdocker環境でやるとしたらどうするのが良いと思いますか？

**Comment by seitaro1227** [comment]
開発ツールから下をDocker環境ベースで書いて見ました。

## 開発ツール

本プロジェクトでは開発ツールとしてDockerとGruntを使用しています。
DockerではGruntを動かす為のnodeやnpmの環境を提供しています。
Gruntが担うタスクは以下の機能になります。
- scssのコンパイル
- tagファイルのコンパイル
- 開発用httpサーバの起動
- リリース用モジュール（ソース圧縮、結合等）の生成

### 開発ツールのインストール
1. [Docker](https://www.docker.com/products/overview)をインストール

## 開発環境準備
1. ソースをチェックアウトし、プロジェクトのディレクトリに移動する

```
$ git clone https://github.com/codeforchiba/feschibal.git
$ cd feschibal
```

## ローカル環境で実行する

```
$ docker run -d -p 9000:9000 -p 35729:35729 -v $(pwd)/app:/var/www/feschibal/app codeforchiba/feschibal
```

以下の URL で動作確認できます。

```
http://localhost:9000/
```

### ローカル環境で開発する

feschibal配下のファイルを更新すると
開発環境を起動している最中はscssファイルもtagファイルも変更を自動で検知し、自動でコンパイルしてくれます。
また、livereload-jsがブラウザを自動でリロードしてくれます。

### お祭りデータをコンバートする

```
$ docker run --rm -v $(pwd)/data:/var/www/feschibal/data -t festival-server-dev grunt build-data
```

**Comment by misopeso** [comment]
@seitaro1227 

リリースモジュールは、Docker Image のことですよね？ 「お祭りデータをコンバートする」でやっているのは、お祭りデータの CSV を JSON に変換することです。ですので、このコマンドラインは、ちょっと違います。お祭りデータとなっていますが、中では必要なマスタデータ(これも、オープンデータです) を JSON に変換することもやってますが、細かい話なのでこのままでもいいかな、と思います。

Docker Image は、厳密にいうとステージング環境用、本番環境用にそれぞれビルドして作成しているので、リリースモジュールの確認はできていません。ただ、ステージング環境用と本番環境用は同じ Dockerfile から Image を作るので、ステージング環境での動作確認をもって、リリースモジュールの確認と考えています。

**Comment by misopeso** [comment]
ただ、現状のシステムはローカルでは確認できないことがない、と思うので、ローカルで確認できればほぼ問題ないと言えます。ですので、README としては、そこまでのいいのかなー と思います。

また、ローカル環境での実行方法は 2種類あるので、その辺追記した方がよいですね。

https://github.com/codeforchiba/feschibal/pull/174#issue-127014194

ちなみに、現状は `CMD ["grunt", "serve:express"]` となっているので、これだと livereload が実行されないと思いますが、その辺どうなってますか？？？

**Comment by misopeso** [comment]
あ、あと、開発環境準備とローカル環境で実行するの間に Docker Image の準備、というのがありますね。

1つは、Docker Hub から pull してくる方法です。

https://hub.docker.com/r/codeforchiba/feschibal/

上記のページに書いてありますが、 `docker pull codeforchiba/feschibal` でダウンロードできます。これが一番簡単です。このイメージは、最新の `develop` ブランチの状態でビルドした Image があります。

もう1つは、自分でビルドすることです。このコマンドですね。

```
docker build -t festival-server-dev:v1 -f Dockerfile.dev .
```

**Comment by seitaro1227** [comment]
@misopeso  さん
回答ありがとうございます。
「リリースモジュール」「お祭りデータをコンバート」について
私なりに理解したところをまとめますと、以下の通りです。

## リリースモジュール

以前Github上で公開していた時代は`grunt build`が必要だったと思います。
これが、Docker環境では公開用のデータがDockerImageにまとめられているので
現状で「リリースモジュール」==「DockerImage」となっている

## お祭りデータをコンバート

feschibalで公開しているデータを更新するのに
csvなどのデータを公開用のフォーマットに変換している。

**Comment by seitaro1227** [comment]
アドバイスありがとうございます。
次の通りまとめて行きます。

## ローカルでの実行方法

node.js + npm + gruntでの開発手法も記載します。

## grunt serve:express

現状で`grunt serve`と`grunt serve:express`にてlivereload-js
が起動しています。

## Docker Image の準備

`docker run`を行う際にpullしていなければ自動でpullされるような動作をしていた為、
省略していました。
しかし、DockerImageの更新を確認する為に明示的に`docker pull`しておいたほうがよいと思うので、省略しない形で書きます。
またそれと合わせて、`docker build`からの`docker run`も記載します。

それと、追っての質問で申し訳ないのですが、「その他Gruntのタスクの記載」について教えてください。

## その他Gruntのタスクの記載

リリースモジュールの生成での`grunt build`と
リリースモジュールでの動作確認での`grunt serve:dist`
これらの記載は、本番環境がDockerである為、削ってしまって大丈夫でしょうか?

**Comment by misopeso** [comment]
@seitaro1227 

リリースモジュールについてですが、結論からいうと README には不要かな、と思います。

> 以前Github上で公開していた時代は grunt build が必要だったと思います。

は、その通りですが、ローカルの開発環境では不要です。また、Docker を使っていても `grunt build` は使います。`grunt build` でリリース用もモジュール一式を作成し、実行環境も含めたものが Docker Image です。

そして、README は誰のために書くのか？ というと、開発者ですよね。README の段階では、開発に着手できればよくて、リリース周りまでは不要だと思います。書くなら別のページかな、と思います。

**Comment by misopeso** [comment]
> 現状でgrunt serveとgrunt serve:expressにてlivereload-js
> が起動しています。

ここ、ちょっと気になるのですが、下記のコードを見ると動かないのかな、と思ってまして。。。

https://github.com/codeforchiba/feschibal/blob/develop/Gruntfile.js#L519-L523

**Comment by misopeso** [comment]
> docker runを行う際にpullしていなければ自動でpullされるような動作をしていた為、省略していました。

`docker run` を実行する際に、ローカルにイメージが見つからない場合、Docker Hub に探しにいきます。ですので、  `codeforchiba/feschibal` で実行した場合は、確かに `docker pull` しなくても OK です。しかし、他の箇所では、 `-t festival-server-dev` と指定していたりして、ややこしいかな、と思ってます。簡単に実行したい場合の例として上げる分にはいいかなー と思います。

**Comment by misopeso** [comment]
> リリースモジュールの生成でのgrunt buildと リリースモジュールでの動作確認でのgrunt serve:dist
> これらの記載は、本番環境がDockerである為、削ってしまって大丈夫でしょうか?

こちらですが、上記に書いたコメントとかぶるかもしれませんが、本番環境が Docker だからではなく、README としては、そこまで不要、という理由でなくていいかな、と思います。

**Comment by seitaro1227** [comment]
@misopeso さん
アドバイスありがとうございます。
それを踏まえて、「開発者がスムーズに開発に着手できること」を目標として書いて見ます。

`grunt serve:express`の件は気になるので、ブレイクポイント貼って処理を追ってみます。

**Comment by seitaro1227** [comment]
一先ずコミットしました。
`grunt serve:express`でのブレイクポイントの件、まだ未確認です。
ローカルで`grunt serve:express`で立ち上げたところ、livereload の grunt taskは動いていないように見えます。

各コマンドについては調べて書きましたが、実際の実行の確認は行っておらず、土日に確認したいです。

**Comment by seitaro1227** [comment]
@misopeso 
コマンドを一通り動かして開発環境を立ち上げられることを確認しました。

`grunt serve:express`の件まだブレイクポイントで確認できていないのです。
動かしている時に気がついたことをまとめます。

## ブラウザのソース

`grunt serve:express`で立ち上げた時にブラウザで表示するソースに
`<script src="//localhost:35729/livereload.js?snipver=1" async="" defer=""></script>`
というコードがありました。

## app.js

https://github.com/codeforchiba/feschibal/blob/develop/app.js#L25-L29
の記述をコメントアウトしたらlivereloadが動作しなくなりました。
Docker.devで`ENV NODE_ENV="development"`としていることから
grunt.js→app.jsの順番で実行されていた場合
もしかしたらそれが原因でlivereloadが実行されているかもしれません。
